services:
  db:
    stop_grace_period: 0s
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  backend:
    stop_grace_period: 0s
    depends_on:
      db:
        condition: service_healthy
    build: backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src/
    env_file: ./global.env

  frontend:
    stop_grace_period: 0s
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src/
    env_file: ./global.env
